import { BunServices } from "@effect/platform-bun";
import { assert, describe, it } from "@effect/vitest";
import {
  Extensions,
  LiftFrontend,
  SourceFrontend,
  compileCollected,
  extension,
  implement,
  lift,
  liftRegistryOf,
  printSuggestion,
  type ProjectConfig,
} from "@effx/compiler";
import { LiftTsSourceFrontend, TsSourceFrontend } from "@effx/frontend-ts";
import { canonical } from "@effx/ir";
import { A, Annotation } from "@effx/runtime";
import { Context, Effect, FileSystem, Layer, Option, Path, Result } from "effect";
import { testDirectory } from "../../../tools/testing/projects.ts";

class RateLimitPolicy extends Context.Service<
  RateLimitPolicy,
  { readonly perMinute: number; readonly burst?: number }
>()("app/RateLimit") {}

const RateLimit = Annotation.define({
  name: "app.RateLimit",
  target: "operation",
  args: { perMinute: A.int, burst: A.optional(A.int) },
  cardinality: "one",
  effect: { target: "endpoint", key: RateLimitPolicy },
});

const repo = new URL("../../../", import.meta.url).pathname;

const services = Layer.mergeAll(TsSourceFrontend.layer, LiftTsSourceFrontend.layer).pipe(
  Layer.provideMerge(BunServices.layer),
);

const extensionValue = extension("app", [implement(RateLimit)]);

const selected = [...Extensions.builtin, extensionValue];

const definitions = new Map(
  selected.flatMap((selectedExtension) =>
    (selectedExtension.annotations ?? []).map(
      (definition) =>
        [definition.name, { plan: definition.plan, target: definition.target }] as const,
    ),
  ),
);

const httpFile = (files: ReadonlyArray<{ readonly path: string; readonly contents: string }>) =>
  files.find((file) => file.path.endsWith("http.ts"));

describe("the real RateLimit generated-HTTP lift journey", () => {
  it.effect(
    "keeps source definition identity, decoded args, canonical IR, and generated bytes",
    () =>
      Effect.gen(function* () {
        const fs = yield* FileSystem.FileSystem;
        const path = yield* Path.Path;
        const directory = yield* testDirectory("lift-rate-limit-");
        const sourceDirectory = path.join(repo, "ai-docs", "src");

        const files = [
          [
            "06_custom-extensions/04_use-annotation.ts",
            "src/06_custom-extensions/04_use-annotation.ts",
          ],
          [
            "06_custom-extensions/03_define-annotation.ts",
            "src/06_custom-extensions/03_define-annotation.ts",
          ],
          ["06_custom-extensions/fixtures/users.ts", "src/06_custom-extensions/fixtures/users.ts"],
          ["01_operations/fixtures/users.ts", "src/01_operations/fixtures/users.ts"],
        ] as const;

        for (const [source, target] of files) {
          const destination = path.join(directory, target);

          yield* fs.makeDirectory(path.dirname(destination), { recursive: true });
          yield* fs.copyFile(path.join(sourceDirectory, source), destination);
        }

        const tsconfigPath = path.join(directory, "tsconfig.json");
        const outputDir = path.join(directory, ".effx", "generated");
        const packageJsonPath = path.join(directory, "package.json");

        yield* fs.writeFileString(
          packageJsonPath,
          '{"private":true,"type":"module","devDependencies":{"typescript":"6.0.3"}}',
        );

        const tsconfig = [
          "{",
          '  "extends": "' + path.join(repo, "tsconfig.json") + '",',
          '  "include": ["src/**/*.ts"],',
          '  "exclude": [],',
          '  "compilerOptions": { "rootDir": "." },',
          '  "effx": { "projectRoot": ".", "outDir": ".effx/generated", "target": "effect-4.0" }',
          "}",
        ].join("\n");

        yield* fs.writeFileString(tsconfigPath, tsconfig);

        const config: ProjectConfig = {
          tsconfigPath,
          projectRoot: directory,
          outDir: outputDir,
          entry: ["src/06_custom-extensions/04_use-annotation.ts"],
          target: "effect-4.0",
          emit: "all",
        };

        const sourceFrontend = yield* SourceFrontend;
        const liftFrontend = yield* LiftFrontend;
        const forwardCollected = yield* sourceFrontend.analyze(config, { definitions });
        const forward = yield* compileCollected(forwardCollected, selected);
        const forwardIr = Option.getOrThrow(forward.ir.value);
        const generated = Option.getOrUndefined(forward.files.value);

        assert.isDefined(
          generated,
          forward.diagnostics
            .map((diagnostic) => `${diagnostic.code}: ${diagnostic.message}`)
            .join("\n"),
        );

        if (generated === undefined)
          return assert.fail("forward compilation must produce generated files");

        const generatedHttp = httpFile(generated);

        assert.isDefined(generatedHttp, generated.map((file) => file.path).join(", "));

        if (generatedHttp === undefined)
          return assert.fail("forward compilation must emit http.ts");

        for (const file of generated) {
          const destination = path.join(outputDir, file.path);

          yield* fs.makeDirectory(path.dirname(destination), { recursive: true });
          yield* fs.writeFileString(destination, file.contents);
        }

        const generatedEntry = path.relative(directory, path.join(outputDir, generatedHttp.path));
        const liftConfig = { ...config, entry: [generatedEntry] };
        const liftedStage = yield* liftFrontend.analyze(liftConfig);
        const model = Option.getOrThrow(liftedStage.value);
        const definition = model.definitions.find((entry) => entry.name === RateLimit.name);

        const lifted = lift(
          model,
          {
            group: "Limited",
            rules: [],
            names: {},
            output: { module: "../../src/recovered.effx.ts" },
          },
          liftRegistryOf(selected),
        );

        const annotation = lifted.collected.declarations
          .flatMap((declaration) => declaration.annotations)
          .find((entry) => entry.name === RateLimit.name);

        assert.isDefined(definition);
        assert.isDefined(annotation);
        assert.deepStrictEqual(annotation?.definition, definition?.ref);
        assert.deepStrictEqual(annotation?.args, [{ perMinute: 60, burst: 5 }]);

        const relifted = yield* compileCollected(lifted.collected, selected);
        const reliftedHttp = httpFile(Option.getOrThrow(relifted.files.value));

        assert.isDefined(reliftedHttp);
        assert.strictEqual(canonical(Option.getOrThrow(relifted.ir.value)), canonical(forwardIr));

        if (reliftedHttp === undefined) return assert.fail("relifting must emit http.ts");

        assert.strictEqual(reliftedHttp.contents, generatedHttp.contents);

        const printed = Result.getOrElse(
          printSuggestion(lifted.collected, { module: "../../src/recovered.effx.ts" }),
          (message) => message,
        );

        const recoveredPath = path.join(directory, "src", "recovered.effx.ts");

        yield* fs.writeFileString(recoveredPath, printed);

        const recoveredCollected = yield* sourceFrontend.analyze(
          { ...config, entry: ["src/recovered.effx.ts"] },
          { definitions },
        );

        const recovered = yield* compileCollected(recoveredCollected, selected);
        const recoveredHttp = httpFile(Option.getOrThrow(recovered.files.value));

        assert.strictEqual(canonical(Option.getOrThrow(recovered.ir.value)), canonical(forwardIr));
        assert.isDefined(recoveredHttp);

        if (recoveredHttp === undefined)
          return assert.fail("recollecting the suggestion must emit http.ts");

        assert.strictEqual(recoveredHttp.contents, generatedHttp.contents);
      }).pipe(Effect.provide(services)),
  );
});
