import { copyUsersFixture } from "../../../tools/testing/projects.ts";
import { BunServices } from "@effect/platform-bun";
import { assert, describe, it } from "@effect/vitest";
import { Extensions, SourceFrontend, compile } from "@effx/compiler";
import { TsSourceFrontend } from "@effx/frontend-ts";
import { canonical, semanticHash } from "@effx/ir";
import { Effect, FileSystem, Layer, Option, Path } from "effect";

const Frontend = TsSourceFrontend.layer.pipe(Layer.provide(BunServices.layer));

const Services = Layer.mergeAll(Frontend, BunServices.layer);

const cases = [
  {
    capability: 'Capability.one("profile.read-self")',
    literal: '{ _tag: "One", capability: "profile.read-self" }',
    concealment: "Concealment.reveal",
    concealmentLiteral: '{ _tag: "Reveal" }',
  },
  {
    capability: 'Capability.any("profile.read-self", "profile.read-other")',
    literal: '{ _tag: "Any", capabilities: ["profile.read-self", "profile.read-other"] }',
    concealment: 'Concealment.notFound("anonymous", "forbidden")',
    concealmentLiteral: '{ _tag: "NotFound", stages: ["anonymous", "forbidden"] }',
  },
  {
    capability: 'Capability.all("profile.read-self", "profile.read-other")',
    literal: '{ _tag: "All", capabilities: ["profile.read-self", "profile.read-other"] }',
    concealment: "Concealment.reveal",
    concealmentLiteral: '{ _tag: "Reveal" }',
  },
  {
    capability: "Capability.none",
    literal: '{ _tag: "None" }',
    concealment: "Concealment.reveal",
    concealmentLiteral: '{ _tag: "Reveal" }',
  },
] as const;

const makeSource = (base: string, variant: (typeof cases)[number], constructors: boolean): string =>
  base
    .replace(
      /import \{ ([^}]+) \} from "@effx\/runtime";/,
      constructors
        ? 'import { Capability as Cap, Concealment as Hide, $1 } from "@effx/runtime";'
        : 'import { $1 } from "@effx/runtime";',
    )
    .replaceAll(
      '{ _tag: "One", capability: "profile.read-self" }',
      constructors ? variant.capability.replace("Capability.", "Cap.") : variant.literal,
    )
    .replaceAll(
      '{ _tag: "One", capability: "profile.update-self" }',
      constructors ? variant.capability.replace("Capability.", "Cap.") : variant.literal,
    )
    .replaceAll(
      '{ _tag: "Reveal" }',
      constructors
        ? variant.concealment.replace("Concealment.", "Hide.")
        : variant.concealmentLiteral,
    );

describe("tagged access source values", () => {
  it.effect(
    "keeps builder and decorator IR, hash, and generated bytes equal to legacy literals",
    () =>
      Effect.gen(function* () {
        const fs = yield* FileSystem.FileSystem;
        const path = yield* Path.Path;
        const fixtureRoot = yield* copyUsersFixture();
        const tsconfigPath = path.join(fixtureRoot, "tsconfig.json");
        const fixture = path.join(fixtureRoot, "src", "_tagged-access.ts");
        yield* Effect.addFinalizer(() => fs.remove(fixture).pipe(Effect.ignore));

        for (const syntax of ["operations.access.builder.ts", "operations.access.ts"]) {
          const base = yield* fs.readFileString(path.join(fixtureRoot, "src", syntax));

          for (const variant of cases) {
            const results = [];

            for (const constructors of [false, true]) {
              yield* fs.writeFileString(fixture, makeSource(base, variant, constructors));

              const result = yield* compile(
                { tsconfigPath, entry: ["src/_tagged-access.ts"] },
                Extensions.builtin,
              );

              assert.deepStrictEqual(
                result.diagnostics.filter((d) => d.severity === "error"),
                [],
              );
              results.push(result);
            }

            const [literal, constructor] = results;
            assert.isDefined(literal);
            assert.isDefined(constructor);
            const left = Option.getOrThrow(literal.ir.value);
            const right = Option.getOrThrow(constructor.ir.value);
            assert.strictEqual(canonical(left), canonical(right));
            assert.strictEqual(yield* semanticHash(left), yield* semanticHash(right));
            const files = Option.getOrThrow(literal.files.value);
            assert.isAbove(files.length, 0);
            assert.deepStrictEqual(Option.getOrThrow(constructor.files.value), files);
          }
        }
      }).pipe(Effect.scoped, Effect.provide(Services)),
    120_000,
  );

  it.effect(
    "rejects lookalikes, dynamic, missing, and empty arguments without access annotations",
    () =>
      Effect.gen(function* () {
        const fs = yield* FileSystem.FileSystem;
        const path = yield* Path.Path;
        const fixtureRoot = yield* copyUsersFixture();
        const tsconfigPath = path.join(fixtureRoot, "tsconfig.json");
        const fixture = path.join(fixtureRoot, "src", "_tagged-invalid.ts");
        yield* fs.writeFileString(
          fixture,
          `
import { Capability, Concealment, Operation } from "@effx/runtime";
const dynamic = (value: string) => value;
let mutable = "mutable";
const CapabilityLookalike = { one: (_value: string) => ({ _tag: "One", capability: "forged" }), none: { _tag: "None" } };
export const staticCap = "static-cap";
export const valid = Operation.query({ name: "valid" }).http.access({ capabilities: Capability.one(staticCap), concealment: Concealment.reveal }).declare();
export const forged = Operation.query({ name: "forged" }).http.access({ capabilities: CapabilityLookalike.one("x") }).declare();
export const forgedValue = Operation.query({ name: "forgedValue" }).http.access({ capabilities: CapabilityLookalike.none }).declare();
export const missing = Operation.query({ name: "missing" }).http.access({ capabilities: Capability.any() }).declare();
export const missingStages = Operation.query({ name: "missingStages" }).http.access({ concealment: Concealment.notFound() }).declare();
export const excess = Operation.query({ name: "excess" }).http.access({ capabilities: Capability.one("a", "b") }).declare();
export const empty = Operation.query({ name: "empty" }).http.access({ capabilities: Capability.one("") }).declare();
export const unknown = Operation.query({ name: "unknown" }).http.access({ concealment: Concealment.notFound(dynamic("x")) }).declare();
export const nonconst = Operation.query({ name: "nonconst" }).http.access({ capabilities: Capability.all(mutable) }).declare();
export const valueCalled = Operation.query({ name: "valueCalled" }).http.access({ capabilities: Capability.none() }).declare();
export const revealCalled = Operation.query({ name: "revealCalled" }).http.access({ concealment: Concealment.reveal() }).declare();
`,
        );
        yield* Effect.addFinalizer(() => fs.remove(fixture).pipe(Effect.ignore));

        const result = yield* SourceFrontend.use((frontend) =>
          frontend.analyze({ tsconfigPath, entry: ["src/_tagged-invalid.ts"] }),
        );

        assert.deepStrictEqual(
          result.declarations
            .find((d) => d.id === "valid")
            ?.annotations.find((a) => a.name === "Http.Access")?.args[0],
          {
            capabilities: { _tag: "One", capability: "static-cap" },
            concealment: { _tag: "Reveal" },
          },
        );

        for (const name of [
          "forged",
          "forgedValue",
          "missing",
          "missingStages",
          "excess",
          "empty",
          "unknown",
          "nonconst",
          "valueCalled",
          "revealCalled",
        ]) {
          assert.isUndefined(
            result.declarations
              .find((d) => d.id === name)
              ?.annotations.find((a) => a.name === "Http.Access"),
            name,
          );
          assert.isTrue(
            result.diagnostics.some((d) => d.code === "EFFX1102" && d.message.includes(name)),
            name,
          );
        }
      }).pipe(Effect.scoped, Effect.provide(Services)),
  );
});
