import { Effect, Option, Schema } from "effect";
import {
  Contribution,
  CompilerFault,
  CoreDiagnostics,
  type Extension,
  type GeneratedFile,
} from "@effx/compiler";
import { IRGraph, Node, StableId } from "@effx/ir";

const name = "example.deprecated";

const dataSchema = Schema.Struct({ reason: Schema.String });

const argsSchema = Schema.Tuple([dataSchema]);

const isData = Schema.is(dataSchema);

const stringJson = Schema.fromJsonString(Schema.String);

/** Static annotation arguments are decoded before contributing semantic IR. */
const interpretDeprecated: Extension["interpreters"][string] = (annotation, declaration, ctx) => {
  const parsed = Schema.decodeUnknownOption(argsSchema)(annotation.args);

  if (Option.isNone(parsed))
    return Contribution.diagnostics(
      CoreDiagnostics["EFFX2902"].emit({ _tag: "Arguments", subject: declaration.id }),
    );

  if (Option.isNone(ctx.operationId))
    return Contribution.diagnostics(
      CoreDiagnostics["EFFX2902"].emit({ _tag: "Operation", subject: declaration.id }),
    );

  const operationId = ctx.operationId.value;
  const id = StableId.make("ext", `${StableId.nameOf(operationId)}/deprecated`);

  const node = Node.make({
    _tag: "Extension",
    id,
    extension: name,
    tag: "Deprecated",
    data: { reason: parsed.value[0].reason },
  });

  return Contribution.make([node], [{ kind: "ExtensionOf", from: id, to: operationId }]);
};

/** Warning only: compilation may still generate the IR-derived declaration. */
const warnDeprecated: Extension["analyses"][number] = (ir, index) =>
  ir.nodes.flatMap((node) => {
    if (node._tag !== "Extension" || node.extension !== name || !isData(node.data)) return [];
    const reason = node.data.reason;

    return IRGraph.outgoing(index, node.id, "ExtensionOf").map((edge) =>
      CoreDiagnostics["EFFX2901"].emit({ operation: StableId.nameOf(edge.to), reason }),
    );
  });

/** Keep authored text inside a single JSDoc line even if the IR contains a newline or closing comment. */
const jsdocText = (reason: string): string => reason.replace(/\s+/gu, " ").replace(/\*\//gu, "* /");

/** Generated bytes are a pure projection of IR and its index, never of the application module. */
const generateDeprecated: Extension["generators"][number] = (ir, index) =>
  Effect.gen(function* () {
    const lines: Array<string> = [];
    let ordinal = 0;

    for (const node of ir.nodes) {
      if (node._tag !== "Extension" || node.extension !== name || !isData(node.data)) continue;

      for (const edge of IRGraph.outgoing(index, node.id, "ExtensionOf")) {
        const owner = IRGraph.nodeOf(index, edge.to);

        if (Option.isNone(owner) || owner.value._tag !== "Operation") continue;

        const encoded = yield* Schema.encodeEffect(stringJson)(owner.value.name).pipe(
          Effect.mapError(
            (cause) =>
              new CompilerFault({
                stage: "generate",
                message: "cannot encode deprecated operation name",
                cause,
              }),
          ),
        );

        lines.push(
          `/** @deprecated ${jsdocText(node.data.reason)} */`,
          `export const deprecated_${ordinal++} = ${encoded} as const;`,
        );
      }
    }

    const files: ReadonlyArray<GeneratedFile> =
      lines.length === 0 ? [] : [{ path: "deprecated.ts", contents: lines.join("\n") + "\n" }];

    return files;
  });

/** No application import: this module is safe to evaluate as a selected config dependency. */
export const deprecatedExtension: Extension = {
  name,
  interpreters: { [name]: interpretDeprecated },
  analyses: [warnDeprecated],
  generators: [generateDeprecated],
};
