// Generated by effx. Do not edit.
// Source: ../../src/operations.client-foldkit#ClientFoldkitProfileOperations.read, ../../src/operations.client-foldkit#ClientFoldkitProfileOperations.update
// IR: operation:Profile.Read, operation:Profile.Update

import { Context, Effect, Layer, Schema } from "effect";
import { FetchHttpClient, HttpClient, HttpClientError, HttpClientRequest } from "effect/http";
import { HttpApiClient, HttpApiMiddleware } from "effect/http-api";
import { CredentialMissing, ProfileCredentialSecurity, profileCommandIdentity } from "../../src/client-foldkit-support.ts";
import { Api } from "./http.ts";

export const operationIndex = [
  {"group":"profile","operationId":"profile.read","method":"GET","path":"/api/profile"},
  {"group":"profile","operationId":"profile.update","method":"PATCH","path":"/api/profile"},
] as const satisfies ReadonlyArray<{
  readonly group: string;
  readonly operationId: string;
  readonly method: string;
  readonly path: string;
}>;

export class TransportFailure extends Schema.TaggedError<TransportFailure>()(
  "TransportFailure",
  { operationId: Schema.String, cause: Schema.Defect() },
) {}

export type ClientCredentials =
  | { readonly kind: "cookie"; readonly cookie: string | (() => string | undefined) }
  | { readonly kind: "bearer"; readonly token: string | (() => string | undefined) }
  | { readonly kind: "custom"; readonly transformClient: (client: HttpClient.HttpClient) => HttpClient.HttpClient };

export interface ClientOptions {
  readonly baseUrl?: string;
  readonly credentials?: ClientCredentials;
}

const withCredentials = (client: HttpClient.HttpClient, credentials: ClientCredentials): HttpClient.HttpClient => {
  if (credentials.kind === "custom") return credentials.transformClient(client);
  return HttpClient.mapRequest(client, (outgoing) => {
    if (credentials.kind === "cookie") {
      const cookie = typeof credentials.cookie === "function" ? credentials.cookie() : credentials.cookie;
      return cookie === undefined || cookie === "" ? outgoing : HttpClientRequest.setHeader(outgoing, "cookie", cookie);
    }
    const token = typeof credentials.token === "function" ? credentials.token() : credentials.token;
    return token === undefined || token === "" ? outgoing : HttpClientRequest.bearerToken(outgoing, token);
  });
};

type ApiClients = {
  readonly "effx": HttpApiClient.ForApi<typeof Api>;
};

type DeclaredFailures = {
  readonly "effx": {
    readonly "profile": {
      readonly "read": typeof CredentialMissing["Type"] | HttpApiMiddleware.Error<typeof ProfileCredentialSecurity>;
      readonly "update": typeof CredentialMissing["Type"] | HttpApiMiddleware.Error<typeof ProfileCredentialSecurity>;
    };
  };
};

type MethodEffect<
  Root extends keyof ApiClients,
  Group extends keyof ApiClients[Root],
  Operation extends keyof ApiClients[Root][Group],
> = ApiClients[Root][Group][Operation] extends (...args: never[]) => infer Result ? Result : never;

export type EffectSdkSuccess<
  Root extends keyof ApiClients,
  Group extends keyof ApiClients[Root],
  Operation extends keyof ApiClients[Root][Group],
> = Effect.Success<MethodEffect<Root, Group, Operation>>;

type KnownNativeFailure<E> = unknown extends E ? never : Exclude<E, HttpClientError.HttpClientError>;

export type EffectSdkFailure<
  Root extends keyof ApiClients,
  Group extends keyof ApiClients[Root] & keyof DeclaredFailures[Root],
  Operation extends keyof ApiClients[Root][Group] & keyof DeclaredFailures[Root][Group],
> =
  | KnownNativeFailure<Effect.Error<MethodEffect<Root, Group, Operation>>>
  | DeclaredFailures[Root][Group][Operation]
  | Schema.SchemaError
  | TransportFailure;

export class Client extends Context.Service<Client, HttpApiClient.ForApi<typeof Api>>()(
  "effx/generated/Client",
) {
  static readonly layer = Layer.effect(Client, HttpApiClient.make(Api));
  static readonly layerWith = (options: ClientOptions) => {
    const credentials = options.credentials;
    return Layer.effect(
      Client,
      HttpApiClient.make(Api, {
        baseUrl: options.baseUrl,
        transformClient: credentials === undefined
          ? undefined
          : (httpClient) => withCredentials(httpClient, credentials),
      }),
    );
  };
  static readonly layerAt = (baseUrl: string) => Client.layerWith({ baseUrl }).pipe(
    Layer.provide(FetchHttpClient.layer),
  );
}

const ProfileReadMiddlewareFailure = (failure: unknown): failure is HttpApiMiddleware.Error<typeof ProfileCredentialSecurity> => {
  for (const codec of ProfileCredentialSecurity.error) {
    if (Schema.is(codec)(failure)) return true;
  }
  return false;
};

export const ProfileRead = (request: Parameters<HttpApiClient.ForApi<typeof Api>["profile"]["read"]>[0]) =>
  Client.use((client) => client["profile"]["read"](
    typeof request !== "object" || request === null ||
    request.responseMode === undefined || request.responseMode === "decoded-only"
      ? request
      : { ...request, responseMode: "decoded-only" },
  ).pipe(
    Effect.mapError((failure) =>
      !HttpClientError.isHttpClientError(failure) && (Schema.isSchemaError(failure) || Schema.is(CredentialMissing)(failure) || ProfileReadMiddlewareFailure(failure))
        ? failure
        : new TransportFailure({ operationId: "profile.read", cause: failure }),
    )
  ));

const ProfileUpdateMiddlewareFailure = (failure: unknown): failure is HttpApiMiddleware.Error<typeof ProfileCredentialSecurity> => {
  for (const codec of ProfileCredentialSecurity.error) {
    if (Schema.is(codec)(failure)) return true;
  }
  return false;
};

export const ProfileUpdate = (request: Parameters<HttpApiClient.ForApi<typeof Api>["profile"]["update"]>[0]) =>
  Client.use((client) => client["profile"]["update"](
    typeof request !== "object" || request === null ||
    request.responseMode === undefined || request.responseMode === "decoded-only"
      ? request
      : { ...request, responseMode: "decoded-only" },
  ).pipe(
    Effect.mapError((failure) =>
      !HttpClientError.isHttpClientError(failure) && (Schema.isSchemaError(failure) || Schema.is(CredentialMissing)(failure) || ProfileUpdateMiddlewareFailure(failure))
        ? failure
        : new TransportFailure({ operationId: "profile.update", cause: failure }),
    )
  ));

export type ProfileUpdateCommandIdentityResult = {
  readonly key: Parameters<HttpApiClient.ForApi<typeof Api>["profile"]["update"]>[0]["headers"]["idempotency-key"];
  readonly input: Parameters<HttpApiClient.ForApi<typeof Api>["profile"]["update"]>[0];
  readonly precondition: Parameters<HttpApiClient.ForApi<typeof Api>["profile"]["update"]>[0]["headers"]["if-match"];
};
export const ProfileUpdateCommandIdentity = (request: Parameters<HttpApiClient.ForApi<typeof Api>["profile"]["update"]>[0]): ProfileUpdateCommandIdentityResult => {
  const identity: ProfileUpdateCommandIdentityResult = profileCommandIdentity(request);
  return { key: request.headers["idempotency-key"], input: identity.input, precondition: request.headers["if-match"] };
};
