// Generated by effx. Do not edit.
// Source: ../../src/operations.client-foldkit#ClientFoldkitProfileOperations.update
// IR: operation:Profile.Update

import { Effect, Schema } from "effect";
import { ProfileUpdateFailed, ProfileUpdateInput, ProfileUpdated, ProfileWriteHeaders } from "../../src/client-foldkit-support.ts";
import { Client, ProfileUpdate } from "./client.ts";
import { Command } from "foldkit";

import type { EffectSdkFailure, EffectSdkSuccess } from "./client.ts";

/** One-shot Commands; the Foldkit runtime owns execution and cancellation. */
export const ProfileCommandsFor = (
  client: Client["Service"],
  adapters: {
    readonly ProfileUpdate: {
      readonly success: (value: { readonly requestId: number; readonly result: EffectSdkSuccess<"effx", "profile", "update"> }) => typeof ProfileUpdated.Type;
      readonly failure: (value: { readonly requestId: number; readonly failure: EffectSdkFailure<"effx", "profile", "update"> }) => typeof ProfileUpdated.Type | typeof ProfileUpdateFailed.Type;
    };
  },
) => ({
  ProfileUpdate: Command.define("ProfileUpdate", {
    args: {
      requestId: Schema.Int,
      request: Schema.Struct({
          headers: ProfileWriteHeaders,
          payload: ProfileUpdateInput,
      }),
    },
    messages: [ProfileUpdated, ProfileUpdateFailed],
    execute: ({ requestId, request }) =>
      ProfileUpdate(request).pipe(
        Effect.provideService(Client, client),
        Effect.map((result) => adapters.ProfileUpdate.success({ requestId, result })),
        Effect.catch((failure) =>
          Effect.succeed(adapters.ProfileUpdate.failure({ requestId, failure })),
        ),
      ),
  }),
});
