// Generated by effx. Do not edit.
// Source: ../../src/operations.client-foldkit#ClientFoldkitProfileOperations.read, ../../src/operations.client-foldkit#ClientFoldkitProfileOperations.update
// IR: operation:Profile.Read, operation:Profile.Update

import { Effect } from "effect";
import { HttpServerRequest } from "effect/http";
import { ClientFoldkitProfileOperations } from "../../src/operations.client-foldkit.ts";

type GuardEffect<Callback> = Callback extends () => Effect.Effect<infer Principal, infer Problem, infer Requirements>
  ? Effect.Effect<Principal, Problem, Requirements> : never;

export type ProfileGuards = {
  readonly "read": (request: HttpServerRequest.HttpServerRequest) => GuardEffect<Parameters<typeof ClientFoldkitProfileOperations.read>[1]>;
  readonly "update": (request: HttpServerRequest.HttpServerRequest) => GuardEffect<Parameters<typeof ClientFoldkitProfileOperations.update>[1]>;
};

export type AppGuards = {
  readonly "effx/profile": ProfileGuards;
};
