// Generated by effx. Do not edit.
// Source: ../../src/operations.client-foldkit#ClientFoldkitInternalOperations.read, ../../src/operations.client-foldkit#ClientFoldkitProfileOperations.read, ../../src/operations.client-foldkit#ClientFoldkitProfileOperations.update
// IR: operation:Internal.ProfileRead, operation:Profile.Read, operation:Profile.Update

import { Effect, Layer, Schema } from "effect";
import { HttpRouter } from "effect/http";
import { HttpApi, HttpApiBuilder, HttpApiEndpoint, HttpApiGroup, HttpApiSchema, OpenApi } from "effect/http-api";
import { ProfileCredentialSecurity, ProfileCurrentPerson, ProfileProblemResponses, ProfileReadHeaders, ProfileReadQuery, ProfileResponse, ProfileResponseHeaders, ProfileUpdateInput, ProfileWriteHeaders, profileAccessAnnotations } from "../../src/client-foldkit-support.ts";
import { ClientFoldkitInternalOperations, ClientFoldkitProfileOperations } from "../../src/operations.client-foldkit.ts";

import type { AppGuards, ProfileGuards } from "./guards.ts";

export class ProfileGroup extends HttpApiGroup.make("profile").add(
  HttpApiEndpoint.get("read", "/api/profile", {
  query: ProfileReadQuery,
  headers: ProfileReadHeaders,
  success: HttpApiSchema.WithHeaders(ProfileResponse, ProfileResponseHeaders),
  error: ProfileProblemResponses("readProblem", ["credential.missing"]),
}).middleware(ProfileCredentialSecurity).annotateMerge(OpenApi.annotations({ identifier: "profile.read" })).annotateMerge(profileAccessAnnotations({ exposure: "External", acceptedCredentials: ["BetterAuthCookie","OAuthUserBearer"], principalKinds: ["Person"], capabilities: {"_tag":"One","capability":"profile.read-self"}, requirements: [{"id":"profile.owner"}], canonicalScopeResolver: ProfileCurrentPerson, concealment: {"_tag":"Reveal"}, decisionTime: "SnapshotRead" })),
  HttpApiEndpoint.patch("update", "/api/profile", {
  headers: ProfileWriteHeaders,
  payload: ProfileUpdateInput,
  success: HttpApiSchema.WithHeaders(ProfileResponse, ProfileResponseHeaders),
  error: ProfileProblemResponses("updateProblem", ["credential.missing"]),
}).middleware(ProfileCredentialSecurity).annotateMerge(OpenApi.annotations({ identifier: "profile.update" })).annotateMerge(profileAccessAnnotations({ exposure: "External", acceptedCredentials: ["BetterAuthCookie","OAuthUserBearer"], principalKinds: ["Person"], capabilities: {"_tag":"One","capability":"profile.update-self"}, requirements: [{"id":"profile.owner"}], canonicalScopeResolver: ProfileCurrentPerson, concealment: {"_tag":"Reveal"}, decisionTime: "Transaction" })),
) {}

export class InternalSecretsGroup extends HttpApiGroup.make("secrets").add(
  HttpApiEndpoint.get("Internal.ProfileRead", "/internal/profile", {
  success: ProfileResponse,
  error: Schema.Never,
}).annotateMerge(profileAccessAnnotations({ exposure: "Internal", acceptedCredentials: ["None"], principalKinds: ["Anonymous"], capabilities: {"_tag":"None"}, requirements: [], canonicalScopeResolver: ProfileCurrentPerson, concealment: {"_tag":"Reveal"}, decisionTime: "SnapshotRead" })),
) {}

export class Api extends HttpApi.make("effx").add(ProfileGroup) {}
export class InternalApi extends HttpApi.make("internal").add(InternalSecretsGroup) {}

export const ProfileHandlers = (guards: ProfileGuards) => HttpApiBuilder.group(
  Api,
  "profile",
  Effect.fn(function* (handlers) {
    return handlers.handleAll({
      "read": ({ request, query, headers }) => ClientFoldkitProfileOperations.read({ ...query, ...headers }, () => guards["read"](request)),
      "update": ({ request, headers, payload }) => ClientFoldkitProfileOperations.update({ ...headers, ...payload }, () => guards["update"](request)),
    });
  }),
);

export const InternalSecretsHandlers = HttpApiBuilder.group(
  InternalApi,
  "secrets",
  Effect.fn(function* (handlers) {
    return handlers.handleAll({
      "Internal.ProfileRead": ({}) => ClientFoldkitInternalOperations.read({}),
    });
  }),
);

export const AppRoutes = (guards: AppGuards) => HttpRouter.serve(Layer.mergeAll(HttpApiBuilder.layer(Api).pipe(Layer.provide([ProfileHandlers(guards["effx/profile"])])), HttpApiBuilder.layer(InternalApi).pipe(Layer.provide([InternalSecretsHandlers]))));
