/**
 * @title Extension skeleton: interpreter, analysis, generator
 *
 * An `Extension` has three parts: interpreters turn annotations into IR
 * contributions, analyses read the IR graph, and generators emit ordinary files.
 */
import {
  Contribution,
  decodeArgs,
  error,
  warning,
  type Analysis,
  type Extension,
  type GeneratedFile,
  type Generator,
  type Interpreter,
} from "@effx/compiler";
import { IRGraph, StableId } from "@effx/ir";
import { Effect, Option, Order, Result, Schema } from "effect";
import * as Arr from "effect/Array";

// The annotation this extension owns is `Audit`, called with one options
// object: `@Annotate("Audit", { level: "sensitive" })`. Argument shape is a Schema, so a
// malformed call becomes a data diagnostic (EFFX1102), never a thrown error.
const AuditLevel = Schema.Literals(["standard", "sensitive"]);

const AuditArgs = Schema.Tuple([Schema.Struct({ level: AuditLevel })]);

// The IR is plain JSON. Define the extension node's `data` as a Schema so the
// analysis and the generator decode it instead of casting.
const AuditPolicyData = Schema.Struct({ level: AuditLevel });

// 1. Interpreter: annotation -> contribution to the IR.
//    It returns nodes, edges and diagnostics. It never returns behaviour.
const interpretAudit: Interpreter = (annotation, declaration, ctx) => {
  // `ctx.operationId` is set when this declaration defines a Query or Command.
  if (Option.isNone(ctx.operationId)) {
    return Contribution.diagnostics(
      error("EFFX9002", `${declaration.id}: the Audit annotation requires an operation`),
    );
  }

  const operation = ctx.operationId.value;

  return Result.match(decodeArgs(AuditArgs, annotation, declaration), {
    onFailure: (diagnostic) => Contribution.diagnostics(diagnostic),
    onSuccess: ([options]) => {
      // One extension node per operation. The id is deterministic.
      const id = StableId.make("ext", `audit/${StableId.nameOf(operation)}`);

      return Contribution.make(
        [
          {
            _tag: "Extension",
            id,
            extension: "audit",
            tag: "AuditPolicy",
            data: { level: options.level },
          },
        ],
        // `ExtensionOf` ties the extension node to its owning operation. The
        // qualifier must equal the extension node's `tag`.
        [{ kind: "ExtensionOf", from: id, to: operation, qualifier: "AuditPolicy" }],
      );
    },
  });
};

// 2. Analysis: read the normalized IR and its graph index, return diagnostics.
//    Diagnostics are data; returning an error diagnostic skips generation.
const unauditedCommands: Analysis = (ir, index) =>
  ir.nodes.flatMap((node) => {
    if (node._tag !== "Operation" || node.kind !== "Command") return [];

    const audited = IRGraph.incoming(index, node.id, "ExtensionOf").some(
      (edge) => edge.qualifier === "AuditPolicy",
    );

    // Pick codes that do not collide with the built-ins (EFFX0001..EFFX2701).
    return audited ? [] : [warning("EFFX9001", `${node.name}: Command has no Audit annotation`)];
  });

// 3. Generator: IR -> files. The output is ordinary TypeScript data. There is
//    no runtime library, and the file must be deterministic.
const generateAuditTable: Generator = (ir, index) => {
  const entries = ir.nodes.flatMap((node) => {
    if (node._tag !== "Extension" || node.extension !== "audit") return [];

    const data = Schema.decodeUnknownOption(AuditPolicyData)(node.data);

    const owner = Option.flatMap(
      Option.fromUndefinedOr(IRGraph.outgoing(index, node.id, "ExtensionOf")[0]),
      (edge) => IRGraph.nodeOf(index, edge.to),
    );

    if (Option.isNone(data) || Option.isNone(owner) || owner.value._tag !== "Operation") {
      return [];
    }

    return [{ operation: owner.value.name, level: data.value.level }];
  });

  // Never emit an empty placeholder file for a missing feature.
  if (entries.length === 0) return Effect.succeed([]);

  const rows = Arr.sort(
    entries,
    Order.mapInput(Order.String, (entry: (typeof entries)[number]) => entry.operation),
  ).map(
    (entry) =>
      `  { operation: ${JSON.stringify(entry.operation)}, level: ${JSON.stringify(entry.level)} },`,
  );

  const file: GeneratedFile = {
    path: "audit.ts",
    contents: [
      "// Generated by the audit extension. Do not edit.",
      "export const auditPolicies = [",
      ...rows,
      "] as const;",
      "",
    ].join("\n"),
  };

  return Effect.succeed([file]);
};

// The extension value. `interpreters` is keyed by annotation name.
export const auditExtension: Extension = {
  name: "audit",
  interpreters: { Audit: interpretAudit },
  analyses: [unauditedCommands],
  generators: [generateAuditTable],
};
