import { Effect, Option } from "effect";
import {
  Extensions,
  compileCollected,
  hasErrors,
  lift,
  liftRegistryOf,
  type Collected,
  type CompileResult,
  type LiftResult,
} from "@effx/compiler";
import { modelOf } from "./lift-source.ts";
import { collectedOf, liftInput, universe, type GroupSpec } from "./lift-universe.ts";

/*
 * The real chain every law of spec 0019 §2.5 runs over: a group of the universe is compiled and generated by
 * the one HTTP generator, its printed source is lowered by the test frontend, and the pure core lifts that
 * model. Nothing on this path is a stand-in for the core or the generator.
 */

export const compiled = (collected: Collected) => compileCollected(collected, Extensions.builtin);

export interface Roundtrip {
  readonly original: CompileResult;
  readonly lifted: LiftResult;
}

export const roundtrip = Effect.fnUntraced(function* (spec: GroupSpec) {
  const original = yield* compiled(collectedOf(spec));

  if (hasErrors(original.diagnostics))
    return yield* Effect.die(
      new Error(
        `the universe produced errors: ${original.diagnostics.map((entry) => entry.message).join("; ")}`,
      ),
    );

  const files = Option.getOrThrow(original.files.value);

  return {
    original,
    lifted: lift(modelOf(files, universe), liftInput, liftRegistryOf([])),
  } satisfies Roundtrip;
});
