import { assert, describe, it } from "@effect/vitest";
import { Effect, Option } from "effect";
import {
  type Extension,
  Extensions,
  SourceFrontend,
  analyze,
  compile,
  compileCollected,
  interpret,
} from "@effx/compiler";
import { IRGraph, StableId, canonical, make, normalize } from "@effx/ir";
import { edges, nodes } from "../../ir/test/fixtures/users.ts";
import { builderStyle, decoratorStyle, mismatched, queryOverPost } from "./fixtures/users.ts";

/** The ir fixture minus its third-party Extension node, which no builtin interpreter produces. */
const expected = normalize(
  make(
    nodes.filter((node) => node._tag !== "Extension"),
    edges,
  ),
);

const codes = (diagnostics: ReadonlyArray<{ readonly code: string }>) =>
  diagnostics.map((d) => d.code).toSorted();

describe("pipeline", () => {
  it.effect("compiles the User slice to the expected IR with no error diagnostics", () =>
    Effect.gen(function* () {
      const result = yield* compileCollected(decoratorStyle, Extensions.builtin);
      assert.deepStrictEqual(
        result.diagnostics.filter((d) => d.severity === "error"),
        [],
      );
      assert.deepStrictEqual(Option.getOrThrow(result.ir.value), expected);
      assert.isTrue(Option.isSome(result.files.value));
    }),
  );

  it.effect(
    "syntax equivalence: decorator-style and builder-style give identical canonical IR",
    () =>
      Effect.sync(() => {
        const a = interpret(decoratorStyle, Extensions.builtin);
        const b = interpret(builderStyle, Extensions.builtin);
        assert.strictEqual(
          canonical(Option.getOrThrow(a.value)),
          canonical(Option.getOrThrow(b.value)),
        );
        assert.deepStrictEqual(a.diagnostics, b.diagnostics);
      }),
  );

  it.effect("EFFX2201/2202/2302/2303 fire when declarations and inference disagree", () =>
    Effect.gen(function* () {
      const result = yield* compileCollected(mismatched, Extensions.builtin);
      assert.deepStrictEqual(codes(result.diagnostics.filter((d) => d.severity === "error")), [
        "EFFX2201", // changeEmail: SqlError inferred, not declared
        "EFFX2202", // get: SqlError declared, not inferred
        "EFFX2303", // get: UserLeases declared, not required
      ]);
      assert.isTrue(Option.isNone(result.files.value), "errors block generation");
      const ir = Option.getOrThrow(result.ir.value);
      const get = ir.nodes.find((n) => n._tag === "Operation" && n.name === "User.Get");
      assert.isTrue(
        get?._tag === "Operation" &&
          get.errors.inferred === false &&
          get.requirements.inferred === false,
      );
    }),
  );

  it.effect("EFFX2401 fires for a Query exposed over POST", () =>
    Effect.gen(function* () {
      const result = yield* compileCollected(queryOverPost, Extensions.builtin);
      assert.include(codes(result.diagnostics), "EFFX2401");
    }),
  );

  it.effect("unknown annotations and orphan transports are diagnostics, not failures", () =>
    Effect.gen(function* () {
      const result = yield* compileCollected(
        {
          diagnostics: [],
          declarations: [
            {
              id: "X.y",
              kind: "staticMethod",
              module: "x",
              export: "X",
              member: "y",
              annotations: [
                { name: "Nope", args: [] },
                { name: "Http.Get", args: ["/x"] },
              ],
            },
          ],
        },
        Extensions.builtin,
      );

      assert.deepStrictEqual(codes(result.diagnostics), ["EFFX1101", "EFFX1103"]);
    }),
  );

  it.effect("EFFX1003 rejects an extension without an owning edge", () =>
    Effect.sync(() => {
      const ir = make(
        [
          {
            _tag: "Extension",
            id: StableId.make("ext", "example/orphan"),
            extension: "example",
            tag: "Orphan",
            data: {},
          },
        ],
        [],
      );

      const findings = analyze(ir, IRGraph.toGraph(ir), Extensions.builtin);
      assert.include(codes(findings), "EFFX1003");
    }),
  );

  it.effect("generators are deterministic and expose server/client entrypoints", () =>
    Effect.gen(function* () {
      const first = yield* compileCollected(decoratorStyle, Extensions.builtin);
      const second = yield* compileCollected(decoratorStyle, Extensions.builtin);
      const files = Option.getOrThrow(first.files.value);
      assert.deepStrictEqual(
        files.map((f) => f.path),
        ["cli.ts", "client.ts", "http.ts", "rpc.ts"],
      );
      assert.deepStrictEqual(files, Option.getOrThrow(second.files.value));

      for (const file of files) {
        assert.isTrue(file.contents.startsWith("// Generated by effx. Do not edit."), file.path);
      }

      const http = files.find((f) => f.path === "http.ts")!.contents;
      assert.include(http, 'HttpApiEndpoint.get("User.Get", "/users/:id"');
      assert.include(http, 'HttpApiEndpoint.patch("User.ChangeEmail", "/users/:id/email"');
      assert.include(http, 'import { ChangeEmailInput, GetUserInput } from "users/schemas"');
      assert.include(http, "HttpRouter.serve(");
      assert.include(http, "RpcServer.layerHttp(");

      const rpc = files.find((f) => f.path === "rpc.ts")!.contents;
      assert.include(rpc, 'Rpc.make("User.Get"');
      assert.include(rpc, "RpcGroup.make(");
      assert.include(rpc, "OperationsClient");

      const cli = files.find((f) => f.path === "cli.ts")!.contents;
      assert.include(cli, 'Command.make("users")');
      assert.include(cli, "Schema.fromJsonString(GetUserInput)");
      assert.include(cli, "Command.run(root, { version })");

      const client = files.find((f) => f.path === "client.ts")!.contents;
      assert.include(client, "HttpApiClient.make(Api)");
      assert.include(client, "layerAt = (baseUrl: string)");
    }),
  );

  it.effect("generation policy is a projection, not part of normalized IR", () =>
    Effect.gen(function* () {
      const policy: Extension = {
        name: "policy",
        interpreters: {},
        analyses: [],
        generators: [
          (_ir, _index, context) =>
            Effect.succeed([
              {
                path: "policy.ts",
                contents: [
                  context?.target,
                  context?.emit,
                  context?.allowImportingTsExtensions,
                  context?.canonicalImportBase,
                  context?.outputDir,
                ].join("/"),
              },
            ]),
        ],
      };

      const collected = { declarations: [], diagnostics: [] };
      const defaults = yield* compileCollected(collected, [policy]);

      const contract = yield* compileCollected(
        {
          ...collected,
          project: {
            target: "effect-4.0-rc",
            emit: "contract",
            allowImportingTsExtensions: true,
            canonicalImportBase: "/source/.effx/generated",
            outputDir: "/artifacts/contract",
          },
        },
        [policy],
      );

      const handlers = yield* compileCollected(
        {
          ...collected,
          project: {
            target: "effect-4.0-rc",
            emit: "handlers",
            allowImportingTsExtensions: false,
            canonicalImportBase: "/source/.effx/generated",
            outputDir: "/artifacts/handlers",
          },
        },
        [policy],
      );

      assert.strictEqual(
        Option.getOrThrow(defaults.files.value)[0]?.contents,
        "effect-4.0/all/false//",
      );
      assert.strictEqual(
        Option.getOrThrow(contract.files.value)[0]?.contents,
        "effect-4.0-rc/contract/true//source/.effx/generated//artifacts/contract",
      );
      assert.strictEqual(
        Option.getOrThrow(handlers.files.value)[0]?.contents,
        "effect-4.0-rc/handlers/false//source/.effx/generated//artifacts/handlers",
      );
      assert.strictEqual(
        canonical(Option.getOrThrow(defaults.ir.value)),
        canonical(Option.getOrThrow(contract.ir.value)),
      );
      assert.strictEqual(
        canonical(Option.getOrThrow(contract.ir.value)),
        canonical(Option.getOrThrow(handlers.ir.value)),
      );
    }),
  );

  it.effect("compile goes through the SourceFrontend service", () =>
    Effect.gen(function* () {
      const result = yield* compile({ tsconfigPath: "./tsconfig.json" }, Extensions.builtin);
      assert.deepStrictEqual(Option.getOrThrow(result.ir.value), expected);
    }).pipe(Effect.provide(SourceFrontend.fromCollected(decoratorStyle))),
  );
});
