import { Array as Arr, Effect, Option, Order, Predicate } from "effect";
import {
  type ApplicationIR,
  type ExposureNode,
  type GraphIndex,
  IRGraph,
  type OperationNode,
  type SchemaRef,
  StableId,
  type SymbolRef,
  type Transport,
} from "@effx/ir";
import { CompilerFault } from "../CompilerFault.ts";
import {
  defaultGenerationContext,
  type GeneratedFile,
  type GenerationContext,
} from "../Extension.ts";
import { moduleSpecifier } from "./target.ts";
import {
  type MethodCall,
  type NameOf,
  type RefLike,
  type Term,
  arr,
  call,
  member,
  printTerm,
  ref,
  refKey,
} from "./term.ts";

/*
 * Shared, pure string building for the generators (ADR 0008). Nothing here touches
 * services or the filesystem; the pipeline writes the files.
 *
 * Effect API facts the generated code relies on (effect 4.0.0, installed sources):
 * - `HttpApiEndpoint.get/post/put/patch/delete(identifier, path, { params, payload, success, error })`
 *   src/http-api/HttpApiEndpoint.ts:1048-1081 (`delete` is `del` re-exported at :1508-1517).
 *   For no-body methods (`GET`, src/http/HttpMethod.ts:45) `payload` must be a field record
 *   (`PayloadConstraintCodecs`, HttpApiEndpoint.ts:1005-1007), so GET endpoints get `<Input>.fields`
 *   (`Schema.Struct.fields` at src/Schema.ts:3380, `Schema.Class.fields` at :14664).
 * - `HttpApiGroup.make(id)` src/http-api/HttpApiGroup.ts:415; `HttpApi.make(id)` src/http-api/HttpApi.ts:235.
 * - `HttpApiBuilder.group(api, groupId, (handlers) => ...)` src/http-api/HttpApiBuilder.ts:130-145;
 *   `handlers.handleAll({ [identifier]: ({ params, payload }) => ... })` :359-367.
 * - `HttpApiClient.make(api, options?)` src/http-api/HttpApiClient.ts:515-528 requires `HttpClient`;
 *   `HttpApiClient.ForApi<typeof Api>` :71-73; client shape `client[groupId][endpointId](request)` :52-55,134-138.
 * - `Context.Service<Self, Shape>()(key)` with `static readonly layer = Layer.effect(...)`
 *   ai-docs/src/51_http-server/10_basics.ts:82-108; `Service.use(f)` src/Context.ts:101.
 * - `Rpc.make(tag, { payload, success, error })` src/rpc/Rpc.ts:941-962.
 * - `RpcGroup.make(...rpcs)` src/rpc/RpcGroup.ts:411-413; `group.toLayer(handlers)` :97-110 where each
 *   handler is `(payload, options) => ...` (`HandlersFrom` :191-193, `Rpc.ToHandlerFn` src/rpc/Rpc.ts:661-669).
 * - `Command.make(name)` src/cli/Command.ts:734, `Command.make(name, config, handler)` :924-928,
 *   `Command.withSubcommands(self, [...])` :1395-1408; `Flag.String(name)` src/cli/Flag.ts:60,
 *   `Flag.withDescription` :565, `Flag.withSchema(flag, codec<B, string>)` :2164;
 *   `Schema.fromJsonString(schema)` src/Schema.ts:9485-9494.
 */

export const HEADER = "// Generated by effx. Do not edit.";

/** Import collector: named imports plus explicitly aliased bindings, sorted by module and export. */
const rank = (module: string): number =>
  module === "effect" ? 0 : module.startsWith("effect/") ? 1 : 2;

export class Imports {
  private readonly modules = new Map<string, Set<string>>();
  private aliases:
    | Array<{ readonly module: string; readonly exported: string; readonly local: string }>
    | undefined;
  private typeAliases:
    | Array<{ readonly module: string; readonly exported: string; readonly local: string }>
    | undefined;
  private reserved: Set<string> | undefined;
  constructor(private readonly context: GenerationContext = defaultGenerationContext) {}

  /** Registers an import and returns its collision-free local; unoccupied names keep their original bytes. */
  add(module: string, name: string): string {
    const specifier = moduleSpecifier(this.context, module);
    const names = this.modules.get(specifier);

    if (names?.has(name)) return name;

    const alias = this.aliases?.find(
      (binding) => binding.module === specifier && binding.exported === name,
    );

    const occupied = this.occupied(name);

    if (alias !== undefined && (alias.local === name || occupied)) return alias.local;

    if (occupied) return this.addAliased(module, name, name);

    if (names === undefined) {
      this.modules.set(specifier, new Set([name]));
    } else {
      names.add(name);
    }

    return name;
  }

  /** Reserve authored declarations and lexical locals before adding schema imports. */
  reserve(...names: ReadonlyArray<string>): void {
    const reserved = (this.reserved ??= new Set());

    for (const name of names) reserved.add(name);
  }

  private occupied(local: string): boolean {
    if (
      this.reserved?.has(local) ||
      this.aliases?.some((alias) => alias.local === local) ||
      this.typeAliases?.some((alias) => alias.local === local)
    )
      return true;

    for (const names of this.modules.values()) {
      if (names.has(local)) return true;
    }

    return false;
  }

  /** Reserve a collision-free local for an imported root without changing its exported name. */
  addAliased(module: string, exported: string, preferredLocal: string): string {
    const specifier = moduleSpecifier(this.context, module);

    const existing = this.aliases?.find(
      (alias) => alias.module === specifier && alias.exported === exported,
    );

    if (existing !== undefined) return existing.local;

    let local = preferredLocal;

    for (let suffix = 2; ; suffix++) {
      if (!this.occupied(local)) break;
      local = `${preferredLocal}_${suffix}`;
    }

    (this.aliases ??= []).push({ module: specifier, exported, local });

    if (!this.modules.has(specifier)) this.modules.set(specifier, new Set());

    return local;
  }

  /** Reserve a collision-free type-only local; the projected source prints this name in a type. */
  addTypeAliased(module: string, exported: string, preferredLocal: string): string {
    const specifier = moduleSpecifier(this.context, module);

    const existing = this.typeAliases?.find(
      (alias) => alias.module === specifier && alias.exported === exported,
    );

    if (existing !== undefined) return existing.local;

    let local = preferredLocal;

    for (let suffix = 2; ; suffix++) {
      if (!this.occupied(local)) break;

      local = `${preferredLocal}_${suffix}`;
    }

    (this.typeAliases ??= []).push({ module: specifier, exported, local });

    return local;
  }

  /** `effect` first, then `effect/*`, then everything else; modules and names alphabetical. */
  render(): ReadonlyArray<string> {
    const byModule = Order.combine(
      Order.mapInput(Order.Number, ([module]: readonly [string, Set<string>]) => rank(module)),
      Order.mapInput(Order.String, ([module]: readonly [string, Set<string>]) => module),
    );

    const valueLines = Array.from(this.modules, ([module, names]) => [module, names] as const)
      .toSorted(byModule)
      .map(([module, names]) => {
        const bindings = Array.from(names);

        if (this.aliases !== undefined) {
          for (const alias of this.aliases) {
            if (alias.module === module) bindings.push(`${alias.exported} as ${alias.local}`);
          }
        }

        bindings.sort(Order.String);

        return `import { ${bindings.join(", ")} } from "${module}";`;
      });

    const typesByModule = new Map<string, Array<string>>();

    for (const alias of this.typeAliases ?? []) {
      const bindings = typesByModule.get(alias.module) ?? [];
      bindings.push(
        alias.local === alias.exported ? alias.exported : `${alias.exported} as ${alias.local}`,
      );
      typesByModule.set(alias.module, bindings);
    }

    const byTypeModule = Order.combine(
      Order.mapInput(Order.Number, ([module]: readonly [string, ReadonlyArray<string>]) =>
        rank(module),
      ),
      Order.mapInput(Order.String, ([module]: readonly [string, ReadonlyArray<string>]) => module),
    );

    const typeLines = Array.from(typesByModule, ([module, bindings]) => [module, bindings] as const)
      .toSorted(byTypeModule)
      .map(
        ([module, bindings]) =>
          `import type { ${bindings.toSorted(Order.String).join(", ")} } from "${module}";`,
      );

    return [...valueLines, ...typeLines];
  }
}

/** `User.Get` → `UserGet`; anything that is not an identifier character is dropped. */
export const identifier = (name: string): string => {
  const stripped = name.replace(/[^A-Za-z0-9_$]/g, "");

  return stripped.length === 0 || /^[0-9]/.test(stripped) ? `_${stripped}` : stripped;
};

/** Operation name as it appears in `operation:<name>`. */
export const operationName = (operation: OperationNode): string => StableId.nameOf(operation.id);

/** The stable declared symbol name, including static members, independent of import aliases. */
export const schemaName = (ref: SchemaRef): string => {
  const name = StableId.nameOf(ref.symbolId);
  const symbol = name.slice(name.lastIndexOf("/") + 1);

  return symbol.startsWith(`${ref.export}.`) ? symbol : ref.export;
};

/** Preserve the original symbol and static-member suffix while resolving a collision-free local import. */
export const schemaExpr = (imports: Imports, reference: SchemaRef): string => {
  const local = imports.add(reference.module, reference.export);

  return local + schemaName(reference).slice(reference.export.length);
};

/** The static-member path a reference adds to its imported local (`Namespace.User`, `Access.annotator`). */
const refPath = (reference: RefLike): string =>
  "symbolId" in reference
    ? schemaName(reference).slice(reference.export.length)
    : reference.member === undefined
      ? ""
      : `.${reference.member}`;

/** A reference as a term: the imported symbol plus its member path as structural access. */
export const refTerm = (reference: RefLike): Term =>
  refPath(reference)
    .split(".")
    .filter((segment) => segment.length > 0)
    .reduce((term, segment) => member(term, segment), ref(reference));

/** Registers `reference` once (first occurrence wins) and returns its collision-free local. */
export const bindRef = (
  imports: Imports,
  names: Map<string, string>,
  reference: RefLike,
): string => {
  const key = refKey(reference);
  const existing = names.get(key);

  if (existing !== undefined) return existing;
  const local = imports.add(reference.module, reference.export);

  names.set(key, local);

  return local;
};

/** The local-name table for a reference list, in first-occurrence order. */
export const bindRefs = (
  imports: Imports,
  references: ReadonlyArray<RefLike>,
): ReadonlyMap<string, string> => {
  const names = new Map<string, string>();

  for (const reference of references) bindRef(imports, names, reference);

  return names;
};

/** The pure name resolver a printer receives: the registered import local for a reference. */
export const nameOf =
  (names: ReadonlyMap<string, string>): NameOf =>
  (reference) =>
    Option.getOrThrow(Option.fromUndefinedOr(names.get(refKey(reference))));

/** Registers every reference a method-call suffix prints, in print order. */
export const bindCallRefs = (
  imports: Imports,
  names: Map<string, string>,
  suffix: MethodCall,
): void => {
  for (const arg of suffix.args) bindTermRefs(imports, names, arg);
};

/** Registers every reference a term prints, in print order (deduplicated by `bindRef`). */
export const bindTermRefs = (imports: Imports, names: Map<string, string>, term: Term): void => {
  switch (term._tag) {
    case "Lit":
      return;
    case "Ref":
      bindRef(imports, names, term.ref);

      return;
    case "Call":
      bindTermRefs(imports, names, term.callee);

      for (const arg of term.args) bindTermRefs(imports, names, arg);

      return;
    case "Chain":
      bindTermRefs(imports, names, term.head);

      for (const suffix of term.calls) bindCallRefs(imports, names, suffix);

      return;
    case "Member":
    case "OptionalMember":
    case "Paren":
      bindTermRefs(imports, names, term.term);

      return;
    case "Nullish":
      bindTermRefs(imports, names, term.head);

      for (const part of term.tail) bindTermRefs(imports, names, part);

      return;
    case "StrictEqual":
      bindTermRefs(imports, names, term.left);
      bindTermRefs(imports, names, term.right);

      return;
    case "Cond":
      bindTermRefs(imports, names, term.test);
      bindTermRefs(imports, names, term.consequent);
      bindTermRefs(imports, names, term.alternate);

      return;
    case "Obj":
      for (const entry of term.entries) bindTermRefs(imports, names, entry.value);

      return;
    case "Arr":
      for (const item of term.items) bindTermRefs(imports, names, item);

      return;
  }
};

/**
 * The `error:` schema expression plus the references its string form registers, in that exact order: the
 * several-schema case registers the member schemas before `Schema`, as the historical builder did.
 */
export interface ErrorSchemaBuilt {
  readonly term: Term;
  readonly references: ReadonlyArray<RefLike>;
}

export const errorsBuilt = (errors: ReadonlyArray<SchemaRef>): ErrorSchemaBuilt => {
  const [single] = errors;
  const schema: RefLike = { module: "effect", export: "Schema" };

  if (single === undefined) return { term: member(ref(schema), "Never"), references: [schema] };

  if (errors.length === 1) return { term: ref(single), references: [single] };

  return {
    term: call(member(ref(schema), "Union"), [arr(errors.map((error) => ref(error)))]),
    references: [...errors, schema],
  };
};

/** `Schema.Never` for none, the schema itself for one, `Schema.Union([...])` for several. */
export const errorsExpr = (imports: Imports, errors: ReadonlyArray<SchemaRef>): string => {
  const built = errorsBuilt(errors);

  return printTerm(nameOf(bindRefs(imports, built.references)), built.term);
};

/** Calls a handler by SymbolRef; a supplied guard thunk stays lazy until the handler calls it. */
export const handlerCall = (
  imports: Imports,
  handler: SymbolRef,
  args: string,
  guard?: string,
): string => {
  const callee = imports.add(handler.module, handler.export);
  const callArgs = guard === undefined ? args : `${args}, ${guard}`;

  return handler.member === undefined
    ? `${callee}(${callArgs})`
    : `${callee}.${handler.member}(${callArgs})`;
};

/** `/users/:id/email` → `["id"]`; duplicates collapse, order preserved. */
export const pathParams = (path: string): ReadonlyArray<string> =>
  Arr.dedupe(
    path
      .split("/")
      .filter((segment) => segment.startsWith(":"))
      .map((segment) => segment.slice(1)),
  );

export const generated = (path: string, contents: string): GeneratedFile => ({ path, contents });

/** An `Exposure` joined with the `Operation` it exposes. `T` narrows the transport. */
export interface Exposed<T extends Transport = Transport> {
  readonly exposure: ExposureNode;
  readonly transport: T;
  readonly operation: OperationNode;
}

export type HttpTransport = Extract<Transport, { readonly _tag: "http" }>;

export type RpcTransport = Extract<Transport, { readonly _tag: "rpc" }>;

export type CliTransport = Extract<Transport, { readonly _tag: "cli" }>;

const isExposure = Predicate.isTagged("Exposure");

const isOperation = Predicate.isTagged("Operation");

const byExposureId = Order.mapInput(Order.String, (node: ExposureNode) => node.id);

/**
 * Every exposure of the IR, sorted by StableId, each resolved to its operation. An exposure whose
 * operation is missing or not an `Operation` node is an invariant breach (analysis blocks it), hence a fault.
 */
export const exposed = (
  ir: ApplicationIR,
  index: GraphIndex,
): Effect.Effect<ReadonlyArray<Exposed>, CompilerFault> =>
  Effect.forEach(
    ir.nodes.flatMap((node) => (isExposure(node) ? [node] : [])).toSorted(byExposureId),
    (exposure) => {
      const operation = IRGraph.nodeOf(index, exposure.operation);

      return Option.isSome(operation) && isOperation(operation.value)
        ? Effect.succeed<Exposed>({
            exposure,
            transport: exposure.transport,
            operation: operation.value,
          })
        : Effect.fail(
            new CompilerFault({
              stage: "generate",
              message: `${exposure.id} exposes ${exposure.operation}, which is not an Operation node in the IR`,
            }),
          );
    },
  );

const symbolText = (symbol: SymbolRef): string =>
  symbol.member === undefined
    ? `${symbol.module}#${symbol.export}`
    : `${symbol.module}#${symbol.export}.${symbol.member}`;

const listing = (items: ReadonlyArray<string>): string =>
  items.length === 0 ? "(none)" : Arr.dedupe(items).toSorted(Order.String).join(", ");

/** The three header lines ADR 0008 requires: marker, handler sources, operation ids. */
export const header = (items: ReadonlyArray<Exposed>): ReadonlyArray<string> => [
  HEADER,
  `// Source: ${listing(items.flatMap((item) => (item.operation.handler === undefined ? [] : [symbolText(item.operation.handler)])))}`,
  `// IR: ${listing(items.map((item) => item.operation.id))}`,
];

/** Joins header, imports and body into file contents; `body` empty → `export {}`. */
export const render = (
  headerLines: ReadonlyArray<string>,
  imports: Imports,
  body: ReadonlyArray<string>,
): string => {
  const importLines = imports.render();
  const sections: Array<ReadonlyArray<string>> = [headerLines];

  if (importLines.length > 0) sections.push(importLines);
  sections.push(body.length === 0 ? ["export {};"] : body);

  return `${sections.map((lines) => lines.join("\n")).join("\n\n")}\n`;
};

export const indent = (lines: ReadonlyArray<string>, level = 1): ReadonlyArray<string> =>
  lines.map((line) => (line.length === 0 ? line : `${"  ".repeat(level)}${line}`));
