import { Array as Arr, Effect, Option, Order, Predicate } from "effect";
import {
  type ApplicationIR,
  type ExposureNode,
  type GraphIndex,
  IRGraph,
  type OperationNode,
  type SchemaRef,
  StableId,
  type SymbolRef,
  type Transport,
} from "@effx/ir";
import { CompilerFault } from "../CompilerFault.ts";
import {
  defaultGenerationContext,
  type GeneratedFile,
  type GenerationContext,
} from "../Extension.ts";
import { moduleSpecifier } from "./target.ts";

/*
 * Shared, pure string building for the generators (ADR 0008). Nothing here touches
 * services or the filesystem; the pipeline writes the files.
 *
 * Effect API facts the generated code relies on (effect 4.0.0, installed sources):
 * - `HttpApiEndpoint.get/post/put/patch/delete(identifier, path, { params, payload, success, error })`
 *   src/http-api/HttpApiEndpoint.ts:1048-1081 (`delete` is `del` re-exported at :1508-1517).
 *   For no-body methods (`GET`, src/http/HttpMethod.ts:45) `payload` must be a field record
 *   (`PayloadConstraintCodecs`, HttpApiEndpoint.ts:1005-1007), so GET endpoints get `<Input>.fields`
 *   (`Schema.Struct.fields` at src/Schema.ts:3380, `Schema.Class.fields` at :14664).
 * - `HttpApiGroup.make(id)` src/http-api/HttpApiGroup.ts:415; `HttpApi.make(id)` src/http-api/HttpApi.ts:235.
 * - `HttpApiBuilder.group(api, groupId, (handlers) => ...)` src/http-api/HttpApiBuilder.ts:130-145;
 *   `handlers.handleAll({ [identifier]: ({ params, payload }) => ... })` :359-367.
 * - `HttpApiClient.make(api, options?)` src/http-api/HttpApiClient.ts:515-528 requires `HttpClient`;
 *   `HttpApiClient.ForApi<typeof Api>` :71-73; client shape `client[groupId][endpointId](request)` :52-55,134-138.
 * - `Context.Service<Self, Shape>()(key)` with `static readonly layer = Layer.effect(...)`
 *   ai-docs/src/51_http-server/10_basics.ts:82-108; `Service.use(f)` src/Context.ts:101.
 * - `Rpc.make(tag, { payload, success, error })` src/rpc/Rpc.ts:941-962.
 * - `RpcGroup.make(...rpcs)` src/rpc/RpcGroup.ts:411-413; `group.toLayer(handlers)` :97-110 where each
 *   handler is `(payload, options) => ...` (`HandlersFrom` :191-193, `Rpc.ToHandlerFn` src/rpc/Rpc.ts:661-669).
 * - `Command.make(name)` src/cli/Command.ts:734, `Command.make(name, config, handler)` :924-928,
 *   `Command.withSubcommands(self, [...])` :1395-1408; `Flag.String(name)` src/cli/Flag.ts:60,
 *   `Flag.withDescription` :565, `Flag.withSchema(flag, codec<B, string>)` :2164;
 *   `Schema.fromJsonString(schema)` src/Schema.ts:9485-9494.
 */

export const HEADER = "// Generated by effx. Do not edit.";

/** Import collector: named imports plus explicitly aliased bindings, sorted by module and export. */
const rank = (module: string): number =>
  module === "effect" ? 0 : module.startsWith("effect/") ? 1 : 2;

export class Imports {
  private readonly modules = new Map<string, Set<string>>();
  private aliases:
    | Array<{ readonly module: string; readonly exported: string; readonly local: string }>
    | undefined;
  constructor(private readonly context: GenerationContext = defaultGenerationContext) {}

  /** Registers `name` from `module` and returns `name` so call sites can inline it. */
  add(module: string, name: string): string {
    const specifier = moduleSpecifier(this.context, module);
    const names = this.modules.get(specifier);

    if (names === undefined) {
      this.modules.set(specifier, new Set([name]));
    } else {
      names.add(name);
    }

    return name;
  }

  /** Reserve a collision-free local for an imported root without changing its exported name. */
  addAliased(module: string, exported: string, preferredLocal: string): string {
    const specifier = moduleSpecifier(this.context, module);

    const existing = this.aliases?.find(
      (alias) => alias.module === specifier && alias.exported === exported,
    );

    if (existing !== undefined) return existing.local;

    let local = preferredLocal;

    for (let suffix = 2; ; suffix++) {
      let occupied = this.aliases?.some((alias) => alias.local === local) ?? false;

      if (!occupied) {
        for (const names of this.modules.values()) {
          if (!names.has(local)) continue;
          occupied = true;
          break;
        }
      }

      if (!occupied) break;
      local = `${preferredLocal}_${suffix}`;
    }

    (this.aliases ??= []).push({ module: specifier, exported, local });

    if (!this.modules.has(specifier)) this.modules.set(specifier, new Set());

    return local;
  }

  /** `effect` first, then `effect/*`, then everything else; modules and names alphabetical. */
  render(): ReadonlyArray<string> {
    const byModule = Order.combine(
      Order.mapInput(Order.Number, ([module]: readonly [string, Set<string>]) => rank(module)),
      Order.mapInput(Order.String, ([module]: readonly [string, Set<string>]) => module),
    );

    return Array.from(this.modules, ([module, names]) => [module, names] as const)
      .toSorted(byModule)
      .map(([module, names]) => {
        const bindings = Array.from(names);

        if (this.aliases !== undefined) {
          for (const alias of this.aliases) {
            if (alias.module === module) bindings.push(`${alias.exported} as ${alias.local}`);
          }
        }

        bindings.sort(Order.String);

        return `import { ${bindings.join(", ")} } from "${module}";`;
      });
  }
}

/** `User.Get` → `UserGet`; anything that is not an identifier character is dropped. */
export const identifier = (name: string): string => {
  const stripped = name.replace(/[^A-Za-z0-9_$]/g, "");

  return stripped.length === 0 || /^[0-9]/.test(stripped) ? `_${stripped}` : stripped;
};

/** Operation name as it appears in `operation:<name>`. */
export const operationName = (operation: OperationNode): string => StableId.nameOf(operation.id);

/**
 * Expression referencing a SchemaRef, registering its import. Symbol IDs use projectRoot-relative
 * identity paths; modules use the canonical import base until the import collector rebases them.
 * Compare only the final symbol segment to preserve static members such as User.Public.
 */
export const schemaExpr = (imports: Imports, ref: SchemaRef): string => {
  imports.add(ref.module, ref.export);
  const name = StableId.nameOf(ref.symbolId);
  const symbol = name.slice(name.lastIndexOf("/") + 1);

  return symbol.startsWith(`${ref.export}.`) ? symbol : ref.export;
};

/** `Schema.Never` for none, the schema itself for one, `Schema.Union([...])` for several. */
export const errorsExpr = (imports: Imports, errors: ReadonlyArray<SchemaRef>): string => {
  const [single] = errors;

  if (single === undefined) return `${imports.add("effect", "Schema")}.Never`;

  if (errors.length === 1) return schemaExpr(imports, single);
  const members = errors.map((ref) => schemaExpr(imports, ref));

  return `${imports.add("effect", "Schema")}.Union([${members.join(", ")}])`;
};

/** Calls a handler by SymbolRef; a supplied guard thunk stays lazy until the handler calls it. */
export const handlerCall = (
  imports: Imports,
  handler: SymbolRef,
  args: string,
  guard?: string,
): string => {
  const callee = imports.add(handler.module, handler.export);
  const callArgs = guard === undefined ? args : `${args}, ${guard}`;

  return handler.member === undefined
    ? `${callee}(${callArgs})`
    : `${callee}.${handler.member}(${callArgs})`;
};

/** `/users/:id/email` → `["id"]`; duplicates collapse, order preserved. */
export const pathParams = (path: string): ReadonlyArray<string> =>
  Arr.dedupe(
    path
      .split("/")
      .filter((segment) => segment.startsWith(":"))
      .map((segment) => segment.slice(1)),
  );

export const generated = (path: string, contents: string): GeneratedFile => ({ path, contents });

/** An `Exposure` joined with the `Operation` it exposes. `T` narrows the transport. */
export interface Exposed<T extends Transport = Transport> {
  readonly exposure: ExposureNode;
  readonly transport: T;
  readonly operation: OperationNode;
}

export type HttpTransport = Extract<Transport, { readonly _tag: "http" }>;

export type RpcTransport = Extract<Transport, { readonly _tag: "rpc" }>;

export type CliTransport = Extract<Transport, { readonly _tag: "cli" }>;

const isExposure = Predicate.isTagged("Exposure");

const isOperation = Predicate.isTagged("Operation");

const byExposureId = Order.mapInput(Order.String, (node: ExposureNode) => node.id);

/**
 * Every exposure of the IR, sorted by StableId, each resolved to its operation. An exposure whose
 * operation is missing or not an `Operation` node is an invariant breach (analysis blocks it), hence a fault.
 */
export const exposed = (
  ir: ApplicationIR,
  index: GraphIndex,
): Effect.Effect<ReadonlyArray<Exposed>, CompilerFault> =>
  Effect.forEach(
    ir.nodes.flatMap((node) => (isExposure(node) ? [node] : [])).toSorted(byExposureId),
    (exposure) => {
      const operation = IRGraph.nodeOf(index, exposure.operation);

      return Option.isSome(operation) && isOperation(operation.value)
        ? Effect.succeed<Exposed>({
            exposure,
            transport: exposure.transport,
            operation: operation.value,
          })
        : Effect.fail(
            new CompilerFault({
              stage: "generate",
              message: `${exposure.id} exposes ${exposure.operation}, which is not an Operation node in the IR`,
            }),
          );
    },
  );

const symbolText = (symbol: SymbolRef): string =>
  symbol.member === undefined
    ? `${symbol.module}#${symbol.export}`
    : `${symbol.module}#${symbol.export}.${symbol.member}`;

const listing = (items: ReadonlyArray<string>): string =>
  items.length === 0 ? "(none)" : Arr.dedupe(items).toSorted(Order.String).join(", ");

/** The three header lines ADR 0008 requires: marker, handler sources, operation ids. */
export const header = (items: ReadonlyArray<Exposed>): ReadonlyArray<string> => [
  HEADER,
  `// Source: ${listing(items.flatMap((item) => (item.operation.handler === undefined ? [] : [symbolText(item.operation.handler)])))}`,
  `// IR: ${listing(items.map((item) => item.operation.id))}`,
];

/** Joins header, imports and body into file contents; `body` empty → `export {}`. */
export const render = (
  headerLines: ReadonlyArray<string>,
  imports: Imports,
  body: ReadonlyArray<string>,
): string => {
  const importLines = imports.render();
  const sections: Array<ReadonlyArray<string>> = [headerLines];

  if (importLines.length > 0) sections.push(importLines);
  sections.push(body.length === 0 ? ["export {};"] : body);

  return `${sections.map((lines) => lines.join("\n")).join("\n\n")}\n`;
};

export const indent = (lines: ReadonlyArray<string>, level = 1): ReadonlyArray<string> =>
  lines.map((line) => (line.length === 0 ? line : `${"  ".repeat(level)}${line}`));
