import type { Schema } from "effect";
import type { SchemaRef, SymbolRef } from "@effx/ir";

/*
 * The neutral expression algebra the HTTP generator builds and prints (spec 0019 §8 S2, seam S2). Terms
 * carry the real `SchemaRef`/`SymbolRef` identities the IR already holds, never a resolved name and never a
 * `ts.*` object: import registration and local-name resolution stay outside, at the generator boundary, so
 * construction and printing are pure (ADR 0004/0009, invariant 10). The shape is closed and minimal — only
 * nodes the frozen HTTP expressions actually need, including the S5 status-200 conditional's member,
 * optional-chain, `??`, `===`, parenthesised and higher-order-call forms.
 *
 * Printing is verbatim: a `Paren` node prints the parentheses the generator wrote, and no precedence pass
 * adds or removes any. `parseTerm(print(t)) = t` is a later slice's law (spec 0019 §10 item 2); S2's
 * obligation is that every existing generated byte is reproduced exactly.
 */

/** A reference a term names; the term keeps the identity, the printer resolves it to an import local. */
export type RefLike = SchemaRef | SymbolRef;

/** The import-binding key of a reference: one binding per module/export, independent of any member. */
export const refKey = (ref: RefLike): string => `${ref.module}\u0000${ref.export}`;

/** Resolves a reference to its printed name (collision-free local plus static-member suffix). Pure. */
export type NameOf = (ref: RefLike) => string;

/** One `key: value` entry of an object literal. `key` is the exact key text (already quoted if it must be). */
export interface ObjEntry {
  readonly key: string;
  readonly value: Term;
}

/**
 * How an object literal prints. `"inline"` is the generator's `{ ${join} }` template, which pads an empty
 * object to `{  }`; `"compact"` is the Arg printer's form, which collapses an empty object to `{}`; `"block"`
 * writes one entry per line at two-space indent with a trailing comma (the endpoint options object).
 */
export type ObjLayout = "inline" | "compact" | "block";

/** One method-call suffix (`.<name>(<args>)`), e.g. `.annotate(K, v)` appended to a generated expression. */
export interface MethodCall {
  readonly name: string;
  readonly args: ReadonlyArray<Term>;
}

/**
 * A generated TypeScript expression, structurally. `Call.callee` is itself a term, so higher-order calls
 * (`HttpApiSchema.status(200)(success)`) and chains (`SchemaAST.resolve(s.ast)?.httpApiStatus`) are exact.
 */
export type Term =
  | { readonly _tag: "Lit"; readonly json: Schema.Json }
  | { readonly _tag: "Ref"; readonly ref: RefLike }
  | { readonly _tag: "Call"; readonly callee: Term; readonly args: ReadonlyArray<Term> }
  | { readonly _tag: "Chain"; readonly head: Term; readonly calls: ReadonlyArray<MethodCall> }
  | { readonly _tag: "Member"; readonly term: Term; readonly member: string }
  | { readonly _tag: "OptionalMember"; readonly term: Term; readonly member: string }
  | { readonly _tag: "Nullish"; readonly head: Term; readonly tail: ReadonlyArray<Term> }
  | { readonly _tag: "StrictEqual"; readonly left: Term; readonly right: Term }
  | {
      readonly _tag: "Cond";
      readonly test: Term;
      readonly consequent: Term;
      readonly alternate: Term;
    }
  | { readonly _tag: "Paren"; readonly term: Term }
  | { readonly _tag: "Obj"; readonly entries: ReadonlyArray<ObjEntry>; readonly layout: ObjLayout }
  | { readonly _tag: "Arr"; readonly items: ReadonlyArray<Term> };

export const lit = (json: Schema.Json): Term => ({ _tag: "Lit", json });

export const ref = (reference: RefLike): Term => ({ _tag: "Ref", ref: reference });

export const call = (callee: Term, args: ReadonlyArray<Term>): Term => ({
  _tag: "Call",
  callee,
  args,
});

export const chain = (head: Term, calls: ReadonlyArray<MethodCall>): Term => ({
  _tag: "Chain",
  head,
  calls,
});

export const methodCall = (name: string, args: ReadonlyArray<Term>): MethodCall => ({ name, args });

export const member = (term: Term, name: string): Term => ({ _tag: "Member", term, member: name });

export const optionalMember = (term: Term, name: string): Term => ({
  _tag: "OptionalMember",
  term,
  member: name,
});

export const nullish = (head: Term, tail: ReadonlyArray<Term>): Term => ({
  _tag: "Nullish",
  head,
  tail,
});

export const strictEqual = (left: Term, right: Term): Term => ({
  _tag: "StrictEqual",
  left,
  right,
});

export const cond = (test: Term, consequent: Term, alternate: Term): Term => ({
  _tag: "Cond",
  test,
  consequent,
  alternate,
});

export const paren = (term: Term): Term => ({ _tag: "Paren", term });

export const obj = (entries: ReadonlyArray<ObjEntry>, layout: ObjLayout = "compact"): Term => ({
  _tag: "Obj",
  entries,
  layout,
});

export const arr = (items: ReadonlyArray<Term>): Term => ({ _tag: "Arr", items });

const printObj = (names: NameOf, term: Extract<Term, { readonly _tag: "Obj" }>): string => {
  const entries = term.entries.map((entry) => `${entry.key}: ${printTerm(names, entry.value)}`);

  switch (term.layout) {
    case "inline":
      return `{ ${entries.join(", ")} }`;
    case "compact":
      return entries.length === 0 ? "{}" : `{ ${entries.join(", ")} }`;
    case "block":
      return `{\n${term.entries.map((entry) => `  ${entry.key}: ${printTerm(names, entry.value)},`).join("\n")}\n}`;
  }
};

/** Prints a receiverless method-call suffix: `.name(arg, …)`. */
export const printMethodCall = (names: NameOf, call_: MethodCall): string =>
  `.${call_.name}(${call_.args.map((arg) => printTerm(names, arg)).join(", ")})`;

/** Prints a term exactly as the generator wrote it; `names` resolves references and nothing else. Pure. */
export const printTerm = (names: NameOf, term: Term): string => {
  switch (term._tag) {
    case "Lit":
      return JSON.stringify(term.json);
    case "Ref":
      return names(term.ref);
    case "Call":
      return `${printTerm(names, term.callee)}(${term.args.map((arg) => printTerm(names, arg)).join(", ")})`;
    case "Chain":
      return (
        printTerm(names, term.head) +
        term.calls.map((call_) => printMethodCall(names, call_)).join("")
      );
    case "Member":
      return `${printTerm(names, term.term)}.${term.member}`;
    case "OptionalMember":
      return `${printTerm(names, term.term)}?.${term.member}`;
    case "Nullish":
      return [term.head, ...term.tail].map((part) => printTerm(names, part)).join(" ?? ");
    case "StrictEqual":
      return `${printTerm(names, term.left)} === ${printTerm(names, term.right)}`;
    case "Cond":
      return `${printTerm(names, term.test)} ? ${printTerm(names, term.consequent)} : ${printTerm(names, term.alternate)}`;
    case "Paren":
      return `(${printTerm(names, term.term)})`;
    case "Obj":
      return printObj(names, term);
    case "Arr":
      return `[${term.items.map((item) => printTerm(names, item)).join(", ")}]`;
  }
};
